--  For ATR 72(Flight ID : 23)  74 seats
INSERT INTO seats (seat_number, class, seat_status, aircraft_id, flight_id, is_booked)
VALUES
('A1', 'FIRST', 'AVAILABLE', 11, 4,0),
('B1', 'FIRST', 'AVAILABLE', 11, 4,0),
('C1', 'FIRST', 'AVAILABLE', 11, 4,0),
('D1', 'FIRST', 'AVAILABLE', 11, 4,0),
('E1', 'FIRST', 'AVAILABLE', 11, 4,0),
('F1', 'FIRST', 'AVAILABLE', 11, 4,0),

('A2', 'FIRST', 'AVAILABLE', 11, 4,0),
('B2', 'FIRST', 'AVAILABLE', 11, 4,0),
('C2', 'FIRST', 'AVAILABLE', 11, 4,0),
('D2', 'FIRST', 'AVAILABLE', 11, 4,0),
('E2', 'FIRST', 'AVAILABLE', 11, 4,0),
('F2', 'FIRST', 'AVAILABLE', 11, 4,0);

INSERT INTO seats (seat_number, class, seat_status, aircraft_id, flight_id, is_booked)
VALUES
('A3', 'BUSINESS', 'AVAILABLE', 11, 4,0),
('B3', 'BUSINESS', 'AVAILABLE', 11, 4,0),
('C3', 'BUSINESS', 'AVAILABLE', 11, 4,0),
('D3', 'BUSINESS', 'AVAILABLE', 11, 4,0),
('E3', 'BUSINESS', 'AVAILABLE', 11, 4,0),
('F3', 'BUSINESS', 'AVAILABLE', 11, 4,0),

('A4', 'BUSINESS', 'AVAILABLE', 11, 4,0),
('B4', 'BUSINESS', 'AVAILABLE', 11, 4,0),
('C4', 'BUSINESS', 'AVAILABLE', 11, 4,0),
('D4', 'BUSINESS', 'AVAILABLE', 11, 4,0),
('E4', 'BUSINESS', 'AVAILABLE', 11, 4,0),
('F4', 'BUSINESS', 'AVAILABLE', 11, 4,0);

INSERT INTO seats (seat_number, class, seat_status, aircraft_id, flight_id, is_booked)
VALUES
('A5', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('B5', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('C5', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('D5', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('E5', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('F5', 'ECONOMY', 'AVAILABLE', 11, 4,0),

('A6', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('B6', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('C6', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('D6', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('E6', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('F6', 'ECONOMY', 'AVAILABLE', 11, 4,0),

('A7', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('B7', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('C7', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('D7', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('E7', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('F7', 'ECONOMY', 'AVAILABLE', 11, 4,0),

('A8', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('B8', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('C8', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('D8', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('E8', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('F8', 'ECONOMY', 'AVAILABLE', 11, 4,0),

('A9', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('B9', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('C9', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('D9', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('E9', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('F9', 'ECONOMY', 'AVAILABLE', 11, 4,0),

('A10', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('B10', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('C10', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('D10', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('E10', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('F10', 'ECONOMY', 'AVAILABLE', 11, 4,0),

('A11', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('B11', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('C11', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('D11', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('E11', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('F11', 'ECONOMY', 'AVAILABLE', 11, 4,0),

('A12', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('B12', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('C12', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('D12', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('E12', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('F12', 'ECONOMY', 'AVAILABLE', 11, 4,0),

('A13', 'ECONOMY', 'AVAILABLE', 11, 4,0),
('B13', 'ECONOMY', 'AVAILABLE', 11, 4,0);

-- ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

--  For ATR 72(Flight ID : 43)  74 seats
INSERT INTO seats (seat_number, class, seat_status, aircraft_id, flight_id, is_booked)
VALUES
('A1', 'FIRST', 'AVAILABLE', 11, 43,0),
('B1', 'FIRST', 'AVAILABLE', 11, 43,0),
('C1', 'FIRST', 'AVAILABLE', 11, 43,0),
('D1', 'FIRST', 'AVAILABLE', 11, 43,0),
('E1', 'FIRST', 'AVAILABLE', 11, 43,0),
('F1', 'FIRST', 'AVAILABLE', 11, 43,0),

('A2', 'FIRST', 'AVAILABLE', 11, 43,0),
('B2', 'FIRST', 'AVAILABLE', 11, 43,0),
('C2', 'FIRST', 'AVAILABLE', 11, 43,0),
('D2', 'FIRST', 'AVAILABLE', 11, 43,0),
('E2', 'FIRST', 'AVAILABLE', 11, 43,0),
('F2', 'FIRST', 'AVAILABLE', 11, 43,0);

INSERT INTO seats (seat_number, class, seat_status, aircraft_id, flight_id, is_booked)
VALUES
('A3', 'BUSINESS', 'AVAILABLE', 11, 43,0),
('B3', 'BUSINESS', 'AVAILABLE', 11, 43,0),
('C3', 'BUSINESS', 'AVAILABLE', 11, 43,0),
('D3', 'BUSINESS', 'AVAILABLE', 11, 43,0),
('E3', 'BUSINESS', 'AVAILABLE', 11, 43,0),
('F3', 'BUSINESS', 'AVAILABLE', 11, 43,0),

('A4', 'BUSINESS', 'AVAILABLE', 11, 43,0),
('B4', 'BUSINESS', 'AVAILABLE', 11, 43,0),
('C4', 'BUSINESS', 'AVAILABLE', 11, 43,0),
('D4', 'BUSINESS', 'AVAILABLE', 11, 43,0),
('E4', 'BUSINESS', 'AVAILABLE', 11, 43,0),
('F4', 'BUSINESS', 'AVAILABLE', 11, 43,0);

INSERT INTO seats (seat_number, class, seat_status, aircraft_id, flight_id, is_booked)
VALUES
('A5', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('B5', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('C5', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('D5', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('E5', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('F5', 'ECONOMY', 'AVAILABLE', 11, 43,0),

('A6', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('B6', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('C6', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('D6', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('E6', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('F6', 'ECONOMY', 'AVAILABLE', 11, 43,0),

('A7', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('B7', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('C7', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('D7', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('E7', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('F7', 'ECONOMY', 'AVAILABLE', 11, 43,0),

('A8', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('B8', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('C8', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('D8', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('E8', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('F8', 'ECONOMY', 'AVAILABLE', 11, 43,0),

('A9', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('B9', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('C9', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('D9', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('E9', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('F9', 'ECONOMY', 'AVAILABLE', 11, 43,0),

('A10', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('B10', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('C10', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('D10', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('E10', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('F10', 'ECONOMY', 'AVAILABLE', 11, 43,0),

('A11', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('B11', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('C11', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('D11', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('E11', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('F11', 'ECONOMY', 'AVAILABLE', 11, 43,0),

('A12', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('B12', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('C12', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('D12', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('E12', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('F12', 'ECONOMY', 'AVAILABLE', 11, 43,0),

('A13', 'ECONOMY', 'AVAILABLE', 11, 43,0),
('B13', 'ECONOMY', 'AVAILABLE', 11, 43,0);


-- ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
--  For A320  180 seats


INSERT INTO seats (seat_number, seat_class, seat_status, aircraft_id, flight_id) VALUES 
('A1', 'FIRST', 'AVAILABLE', 1, NULL),
('B1', 'FIRST', 'AVAILABLE', 1, NULL),
('C1', 'FIRST', 'AVAILABLE', 1, NULL),
('D1', 'FIRST', 'AVAILABLE', 1, NULL),
('E1', 'FIRST', 'AVAILABLE', 1, NULL),
('F1', 'FIRST', 'AVAILABLE', 1, NULL),

('A2', 'FIRST', 'AVAILABLE', 1, NULL),
('B2', 'FIRST', 'AVAILABLE', 1, NULL),
('C2', 'FIRST', 'AVAILABLE', 1, NULL),

('D2', 'FIRST', 'AVAILABLE', 1, NULL),
('E2', 'FIRST', 'AVAILABLE', 1, NULL),
('F2', 'FIRST', 'AVAILABLE', 1, NULL),

('A3', 'FIRST', 'AVAILABLE', 1, NULL),
('B3', 'FIRST', 'AVAILABLE', 1, NULL),
('C3', 'FIRST', 'AVAILABLE', 1, NULL),
('D3', 'FIRST', 'AVAILABLE', 1, NULL),
('E3', 'FIRST', 'AVAILABLE', 1, NULL),
('F3', 'FIRST', 'AVAILABLE', 1, NULL),

('A4', 'FIRST', 'AVAILABLE', 1, NULL),
('B4', 'FIRST', 'AVAILABLE', 1, NULL),
('C4', 'FIRST', 'AVAILABLE', 1, NULL),
('D4', 'FIRST', 'AVAILABLE', 1, NULL),
('E4', 'FIRST', 'AVAILABLE', 1, NULL),
('F4', 'FIRST', 'AVAILABLE', 1, NULL),

('A5', 'FIRST', 'AVAILABLE', 1, NULL),
('B5', 'FIRST', 'AVAILABLE', 1, NULL),
('C5', 'FIRST', 'AVAILABLE', 1, NULL);


INSERT INTO seats (seat_number, seat_class, seat_status, aircraft_id, flight_id) VALUES 
('D5', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('E5', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('F5', 'BUSINESS', 'AVAILABLE', 1, NULL),

('A6', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('B6', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('C6', 'BUSINESS', 'AVAILABLE', 1, NULL),
('D6', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('E6', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('F6', 'BUSINESS', 'AVAILABLE', 1, NULL),

('A7', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('B7', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('C7', 'BUSINESS', 'AVAILABLE', 1, NULL),
('D7', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('E7', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('F7', 'BUSINESS', 'AVAILABLE', 1, NULL),

('A8', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('B8', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('C8', 'BUSINESS', 'AVAILABLE', 1, NULL),
('D8', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('E8', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('F8', 'BUSINESS', 'AVAILABLE', 1, NULL),

('A9', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('B9', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('C9', 'BUSINESS', 'AVAILABLE', 1, NULL),
('D9', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('E9', 'BUSINESS', 'AVAILABLE', 1, NULL), 
('F9', 'BUSINESS', 'AVAILABLE', 1, NULL);


INSERT INTO seats (seat_number, seat_class, seat_status, aircraft_id, flight_id) VALUES 
('A10', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('B10', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('C10', 'ECONOMY', 'AVAILABLE', 1, NULL),
('D10', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('E10', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('F10', 'ECONOMY', 'AVAILABLE', 1, NULL),

('A11', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('B11', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('C11', 'ECONOMY', 'AVAILABLE', 1, NULL),
('D11', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('E11', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('F11', 'ECONOMY', 'AVAILABLE', 1, NULL),

('A12', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('B12', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('C12', 'ECONOMY', 'AVAILABLE', 1, NULL),
('D12', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('E12', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('F12', 'ECONOMY', 'AVAILABLE', 1, NULL),

('A13', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('B13', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('C13', 'ECONOMY', 'AVAILABLE', 1, NULL),
('D13', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('E13', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('F13', 'ECONOMY', 'AVAILABLE', 1, NULL),

('A14', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('B14', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('C14', 'ECONOMY', 'AVAILABLE', 1, NULL),
('D14', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('E14', 'ECONOMY', 'AVAILABLE', 1, NULL), 
('F14', 'ECONOMY', 'AVAILABLE', 1, NULL);

